
export const FETCH_REGISTER_REQUEST = 'FETCH_REGISTER_REQUEST';

export const FETCH_REGISTER_SUCCESS = 'FETCH_REGISTER_SUCCESS';

export const FETCH_REGISTER_FAILURE = 'FETCH_REGISTER_FAILURE';

export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE';

export const SHOW_ERROR_MESSAGE = 'SHOW_ERROR_MESSAGE';

export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';

export const RESET_CHAT_INPUT = 'RESET_CHAT_INPUT';

export const CHANGE_CHAT_INPUT = 'CHANGE_CHAT_INPUT';

export const FETCH_MESSAGES_REQUEST = 'FETCH_MESSAGES_REQUEST';

export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS';

export const FETCH_MESSAGES_FAILURE = 'FETCH_MESSAGES_FAILURE';
