
export const FETCH_REGISTER_SUCCESS = 'FETCH_REGISTER_SUCCESS';

export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS';

// export const FETCH_LOGOUT_SUCCESS = 'FETCH_LOGOUT_SUCCESS';
export const LOGOUT = 'LOGOUT';

export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE';

export const SHOW_ERROR_MESSAGE = 'SHOW_ERROR_MESSAGE';

export const actionTypeTemplates = {
  FETCH_ITEMS_REQUEST: 'FETCH_ITEMS_REQUEST',
  FETCH_ITEMS_SUCCESS: 'FETCH_ITEMS_SUCCESS',
  FETCH_ITEMS_FAILURE: 'FETCH_ITEMS_FAILURE',
  RECEIVE_ITEM: 'RECEIVE_ITEM',
  RESET_ITEM_INPUT: 'RESET_ITEM_INPUT',
  CHANGE_ITEM_INPUT: 'CHANGE_ITEM_INPUT'
};

export const SET_ACTIVE_CHANNEL = 'SET_ACTIVE_CHANNEL';

export const LOBBY_RECEIVE_USER = 'LOBBY_RECEIVE_USER';
