
export const FETCH_REGISTER_REQUEST = 'FETCH_REGISTER_REQUEST';

export const FETCH_REGISTER_SUCCESS = 'FETCH_REGISTER_SUCCESS';

export const FETCH_REGISTER_FAILURE = 'FETCH_REGISTER_FAILURE';

export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE';

export const SHOW_ERROR_MESSAGE = 'SHOW_ERROR_MESSAGE';
