
export var SET_TEMPLATE_DATA = 'SET_TEMPLATE_DATA';

export var START_LOGIN_FETCH = 'START_LOGIN_FETCH';

export var COMPLETE_LOGIN_FETCH = 'COMPLETE_LOGIN_FETCH';

export const FETCH_REGISTER_REQUEST = 'FETCH_REGISTER_REQUEST';

export const FETCH_REGISTER_SUCCESS = 'FETCH_REGISTER_SUCCESS';

export const FETCH_REGISTER_FAILURE = 'FETCH_REGISTER_FAILURE';
